version: '3.1'
services:
  wiremock:
    image: rodolpheche/wiremock
    networks:
    - hmpps_int
    container_name: interventions-catalogue-wiremock
    restart: always
    ports:
      - "9091:8080"


networks:
  hmpps_int:
